GH actions update - latest maven, enable native
quarkus-qe/quarkus-extensions-combinations pull request #202
Opened 2023-04-27 08:50 UTC by rsvoboda

2023-05-03 10:16 UTC, jsmrcka requested changes

2023-05-03 10:16 UTC, jsmrcka commented on .github/workflows/daily.yml
> -  linux-build-released-dev:
What is the reason for dropping the dev mode tests?

2023-05-03 10:16 UTC, jsmrcka commented on src/main/resources/exclusions.properties
> +spring-web,rest-client-jsonb=skip-all
We should also add
```suggestion
spring-web,rest-client-jsonb=skip-all
spring-web,rest-client-jaxb=skip-all
spring-web,rest-client=skip-all
```
See failures in https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/job/quarkus-main-rhel8-jdk11-extensions-combinations-ts/117/.

2023-05-04 13:48 UTC, rsvoboda commented on .github/workflows/daily.yml
> -  linux-build-released-dev:
they were never enabled

If you think dev mode ones are needed they can be addressed in separate PR

2023-05-05 09:58 UTC, jsmrcka commented on .github/workflows/daily.yml
> -  linux-build-released-dev:
Oh, I see it now, thanks.

2023-05-05 09:58 UTC, jsmrcka approved these changes

2023-05-05 09:58 UTC, merged